### PR TITLE
Correction highlighted in Issue 39 not fully implemented, so submitting as pull request.

### PR DESCRIPTION
**Pull request by ng110**

### CODE REVIEW

**Comment by indranilsinharoy** [comment]
@ng110 It's my mistake that I didn't make the appropriate fix that you highlighted in Issue 39. Thank very much for submitting the pull request +1:

**Comment by indranilsinharoy** [comment]
@ng110 By the way, lately I have been working on the bulk ray tracing issue. I have a separate branch for it -- https://github.com/indranilsinharoy/PyZDDE/tree/arrayTraceUsingZclient. You seem to be doing some ray tracing using the currently available functions in PyZDDE master, which make a DDE call per ray. I was wondering, if you could see if the bulk ray tracing functions could work for you. Please note that the functions are really very new at this point, and I am not very sure about what is the best way to write these functions. This is the main the reason why I am requesting you to check out if the functions will be ok for what you are doing. In order to use the array ray tracing, please see the example "arrayTraceSimple.py" in the Examples/Scripts folder. It basically emulates ArrayDemo.c example provided by Zemax. The array tracing functions are in the module ``arraytrace`` (please refer to the module docstring for reference). It has 4-5 helper functions to setup the array, and call the 5 array ray tracing modes. Also, note that ``arraytrace`` creates a secondary DDE link with Zemax for array ray tracing that may (not necessary) exist in parallel to a regular pyzdde link. Basically I have taken the core of zclient.c, and built a dll to call the functions using ctypes. This is the only way array ray tracing seems to work right now. Anyways, please let me know if you have any questions/concerns.

Thank you very much.

**Comment by ng110** [comment]
Thanks for that.  Sounds useful.

As you guessed, I have been tracing rays one at a time which works, but is a bit slow and cumbersome.  When I get time, I'll give your new routines a try and see if they match up with the slow method.

Cheers,

Neil.

---- On Thu, 26 Feb 2015 17:19:25 +0000 Indranil Sinharoy &lt;notifications@github.com&gt; wrote ---- 

@ng110 By the way, lately I have been working on the bulk ray tracing issue. I have a separate branch for it -- https://github.com/indranilsinharoy/PyZDDE/tree/arrayTraceUsingZclient. You seem to be doing some ray tracing using the currently available functions in PyZDDE master, which make a DDE call per ray. I was wondering, if you could see if the bulk ray tracing functions could work for you. Please note that the functions are really very new at this point, and I am not very sure about what is the best way to write these functions. This is the main the reason why I am requesting you to check out if the functions will be ok for what you are doing. In order to use the array ray tracing, please see the example "arrayTraceSimple.py" in the Examples/Scripts folder. It basically emulates ArrayDemo.c example provided by Zemax. The arr ay traci ng functions are in the module arraytrace (please refer to the module docstring for reference). It has 4-5 helper functions to setup the array, and call the 5 array ray tracing modes. Also, note that arraytrace creates a secondary DDE link with Zemax for array ray tracing that may (not necessary) exist in parallel to a regular pyzdde link. Basically I have taken the core of zclient.c, and built a dll to call the functions using ctypes. This is the only way array ray tracing seems to work right now. Anyways, please let me know if you have any questions/concerns.
 Thank you very much.

**Comment by indranilsinharoy** [comment]
Thanks, Neil.

**Comment by indranilsinharoy** [comment]
Hi Neil,

I wanted to update you with something that I came across just a few minutes back. I just found that there was another bug in the function ``zGetPolTraceDirect()`` in the line ``args2 = "{x:1.20g},{y:1.20g},{y:1.20g},".format(x=x,y=y,z=z)`` -- you see the ``z`` is getting assigned the value of ``y`` because of the last ``{y:1.20g}``. It should have been `args2 = "{x:1.20g},{y:1.20g},{z:1.20g},".format(x=x,y=y,z=z)``. I am extremely sorry, if you may have to re-run your experiments due to this. 

Regards,
Indranil.

**Pull request merged**
