### PR TITLE
Added basic zrd read and write functionality

### PR DESCRIPTION
**Pull request by olfduh**
- not tested for ray splitting
- only uncompressed ray files
- not sure how to incorporate with the rest of the module. So far I could only use it by adding the path of the pyzrd file manually

### CODE REVIEW

**Comment by indranilsinharoy** [comment]
Hi Olf,

This is great. Nice work. Please note that I will only have some time during the weekend to review it. I will probably also request @CatherineH and @xy124 to review it (if they have the time and interest). This is mostly because of my own lack of knowledge of ZRD files, and constraint of time at present. Other than that, I have few comments based on your files.

1. Is the use of NumPy the only way for working with ZRD files in Python? I it possible to switch back to standard Python modules if NumPy import fails? My motivation is this -- While it is expected that most people using Python for any scientific work will have NumPy, I think that there is some advantage of having zero or less dependency on external libraries. This is the main reason, I have refrained from using Numpy in `zdde.py`. Please note that this is NOT an absolute requirement, but give it a thought.

2. Can you provide a basic example of how to use these two functions?

3.  Can you write a two basic unit-test for the `readZRD()` and `writeZRD()` functions? (in /Test/pyZDDEunittest.py) 

Thanks very much,
Regards,
Indranil.

**Comment by olfduh** [comment]
Hi Indrail,
it should actually easy to remove the numpy dependency. Also I will try to add some more documentation for the functions and add a simple example.

Regards,
Olf

**Comment by indranilsinharoy** [comment]
Hi Olf,

That's great. I will hold off merging till then.

**Comment by olfduh** [comment]
- Numpy dependency has been removed
- I added the compressed zrd file format for reading and writing files
- Unit test still to come
 -> I will just put a small zrd file in the ZMXFiles folder and test if they can be imported and saved to another file
- Documentation still basically not exiting

I keep working on it every now and then :)

**Comment by indranilsinharoy** [comment]
Hi Olf,

Superb! 
I have a small request. I have been thinking about a right place to put the functions (you are adding) and the required data structures in PyZDDE. Here are some thoughts --

1. Since we already have some functions for reading and writing to binary files (e.g. readBeamFile() and writeBeamFile()) in zdde.py, I think it might be better to put the ZRD file read/write functions in zdde.py (I think even you had suggested the same much earlier). If we place different file access functions in different places, it might be hard to find, and will not be uniform from the users perspective.
2. Also, we (or someone else) might add other types of file read/write utilities in the future which may require to write different other types of data structures or utilities for file access. For this reason, I think that we should have a separate but common file (like you have in ``pyzrd.py``) that contains all such  utilities. So, do you think it will be useful to rename ``pyzrd.py`` to something like ``zfileutils.py``?

Please feel fee to shoot me down if you think otherwise :-)

Also, sorry for the trouble.

Regards,
Indranil.

**Comment by olfduh** [comment]
I think, that it might be better to keep the file input/output functionality in a separate (sub-) module. Something like zfileutls.py of zfileio.py. The file interactions do not depend on the dde communication, so (for me) it would feel more logical to keep it separate. This way, you know if you need to look at the code for some file input/output you just check one file and don't have to think where a certain function might hide. Also these functionalities could be interesting for applications where no interaction with Zemax is required, such as some advanced analysis of non-sequential simulation results.

Just my 2 cents

**Comment by indranilsinharoy** [comment]
>I think, that it might be better to keep the file input/output functionality in a separate (sub-) module. Something like zfileutls.py of zfileio.py. The file interactions do not depend on the dde communication, so (for me) it would feel more logical to keep it separate.
>....
>....
>Also these functionalities could be interesting for applications where no interaction with Zemax is required, such as some advanced analysis of non-sequential simulation results.

I completely understand, and really do appreciate the thought above, and it is completely logical. 
Here is the current state of PyZDDE (and probably some justification of why it is the way .... again, I am not saying that this is the absolute right thing to do):

There are already several functions in zdde.py that do not depend on DDE communication. All functions that use the DDE communication with Zemax have 'z' prefixed to their names to distinguish them from other helper functions. Also, the user needs to create a DDE link object in order to call these functions that use the DDE link. The rest of the functions can be called immediately after importing pyzdde.zdde, for example, ``import pyzdde.zdde as pyz``, and then we can call functions such as ``pyz.fresnelNumber()``, ``pyz.findZOperand()``, ``pyz.readBeamFile()``, ``pyz.writeBeamFile()``, etc. We don't even need to have a running Zemax application in order to use these functions. At the same time, from the user's perspective, they don't need to remember the names of different sub-modules within PyZDDE ... all of which being available from the top level. 

Having said that, I also, at times, think that this is probably not optimum too --- as finding the right function when there are too many, might be a problem!! So, I think that you should probably create a separate ``zfileutils.py`` file and place the functions there in working branch. I shall think over it a little more ... but if we need to move forward this way, then now is the time, before it is too late.

A few more comments regarding the class and function naming, before you write all the code. You may have noticed that the function naming in PyZDDE doesn't follow the PEP8 guidelines. This is because I wanted to make the functions more like how they are named in MZDDE. You can use the PEP8 style of class name. Rest everything is shaping up well, I believe. Great job.

Looking forward to seeing your code/files.  

Thanks.
Regards,
Indranil.

**Comment by olfduh** [comment]
Would it also be possible to keep the functions in the same name space and keep the functions in different files? That could be a good way to go.

Regards,

Olf

**Comment by indranilsinharoy** [comment]
Yes, it is possible.

**Comment by olfduh** [comment]
Hey guys,

I finally got around to add the unit test and also did some code documentation. Indranil, maybe you can have a look into it and add it to your repository if you think it is ready for publication?

Best,
Olf

**Comment by indranilsinharoy** [comment]
Hi Olf,

Great! I will go through it tonight, and do the merge asap.

**Comment by indranilsinharoy** [comment]
Hi Olf,

The writeZRD() unit test is failing. Please see the output of the test below.

```Python
TEST: writeZRD()

Write to uncompressed file failed

Write to compressed zrd file failed
```

**Comment by olfduh** [comment]
Hi Indrail,

after a long time I finally found some space to work on the zfileutils. I did the small changes you suggested and updated my repository.
Not sure where th eproblem of the unit test lies. I added a test program in the Test folder. This runs on my machine without errors, maybe you can try that as well and send me possible error messages.

Regards,
Olf

**Comment by indranilsinharoy** [comment]
Hi Olf,

Thank you so much. I will check it out tonight and get back to you on this ASAP. 

Best regards,
Indranil.

**Comment by olfduh** [comment]
Hi Indrail,

I tested some other ray files and found that it is not always working. I am trying to figure out what the problem is. Nevertheless please let me know if the test case I added works for you.

Best,
Olf

**Comment by indranilsinharoy** [comment]
Hi olf,

While the test (that was really just testing if the functions and read or write the files) executed without any issue, I wasn't really sure if the written file would match the original file byte-by-byte. So I added a function ``compare_files_nbytes()`` to the ``test_zrd.py`` file. When I compared an original (produced by Zemax) uncompressed ZRD file with the file produced by ``zrdWrite()``  after reading the ZRD file using ``zrdRead()``, I found that the files differed in the bytes 4-5 (last two byte positions for ``max_n_segments``). I guess that you may have (am not sure whether it was intentional) adding the line ``zrd[-1].n_segments = n_segments`` in the ``zrdRead()`` function after extracting ``n_segments``.  Since the line was (perhaps) missing, the re-written zrd file had ``max_n_segments`` equal to the default value (as defined in the ``ZemaxRay`` class definition). 

Also, apart from adding that line to ``zrdRead()`` function, I did some cosmetic changes to the functions (I hope you wouldn't mind it). I haven't tested the functions against compressed zrd file yet. I plan to do it soon. But you done very good job, and thank you for this important contribution. I am very sure it is going to be very useful once it is complete. Since, I didn't want mess up your branch, I spawned a separate branch off of your branch to play with the code. Please have a look here, and feel free to do what you feel appropriate: 

Branch: 
https://github.com/indranilsinharoy/PyZDDE/tree/zrdFuncFromOlf

test_zrd.py
https://github.com/indranilsinharoy/PyZDDE/blob/zrdFuncFromOlf/Test/zfileutils/test_zrd.py

zfileutils.py
https://github.com/indranilsinharoy/PyZDDE/blob/zrdFuncFromOlf/pyzdde/zfileutils.py

I will play with the compressed files soon and see what's going on with it.

Best regards,
Indranil.

**Comment by indranilsinharoy** [comment]
Hi Olf,

I created a couple of compressed (basic) ZRD files using Zemax, and tried to read the data using the ``zrdRead()`` function. However, it failed, causing a Memory Error. On closer inspection, it seems that the function is not reading the `n_segment` data correctly the second time around. I have put a (temporary) check in the ``zrdRead()`` function to stop reading the file and break out of the loop when than happens (to prevent the system from hanging). Here is a sample output from executing the file ``test_zrd.py``.

```python
FORMER TEST FUNCTIONS
Former test functions successful

TEST FOR UNCOMPRESSED FULL FILE
Number of segments in the uncompressed ZRD file =  10
Files match

TEST FOR COMPRESSED BASIC FILE
n_segments (473759744) > 50 at byte-offset position 252. Closing file and exiting
```

I am not sure why this is happening. When I read the Zemax manual it seemed to me that every ray would occupy 40 bytes (4 each for `status`, `level`, `hit_object`, `parent`, `xybin`, `lmbin`, `x`, `y`, `z`, `intensity`), and there are 6 segments for the first ray making a total of 240 bytes. Then, since there are 12 bytes at the beginning of the file (for `Version`, `max_n_segments`, `n_segments`), I would have expected to indeed read the next value for `n_segments` (that follows) in the byte position 252-255. However, that is certainly not what is happening. Any clues?

**Comment by olfduh** [comment]
Indrail,

good point about the n_segments, this is really missing. I found a note in the Zemax help which might be the reason whe the cbd file gives trouble. In the description for the cbd zrd file format it states:

>CBD files are dynamically compressed in a way that makes the file unsuitable for read/write operations outside of Zemax.

I still believe it should somehow be possible to import it, as Zemax can do so. But without them disclosing the compressing algorithm it might be very difficult

The cfd file format still should work, as it is stated inthe help that it countains all information of the ufd but in float instead of double. Still, I couldn't sucessfully import a cfd file. It seems to read in the first ray sucessfully and then it somehow runs into errors.

Regards,

Olf

**Comment by indranilsinharoy** [comment]
Hi Olf,

I have a few comments:

1. regarding the compressed ZRD files -- How critical is the ability to read/write ZRD files? Do you think it will be OK to have the uncompressed ZRD file read/write capability (if it is working as expected, and successful in our tests) for now? Will will keep the other two as NOT_IMPLEMENTED (with warning) till we can figure out how to do it. I totally agree with "*I still believe it should somehow be possible to import it, as Zemax can do so. But without them disclosing the compressing algorithm it might be very difficult*"

2. "*The cfd file format still should work, as it is stated in the help that it contains all information of the ufd but in float instead of double. Still, I couldn't successfully import a cfd file. It seems to read in the first ray successfully and then it somehow runs into errors*." --- I am pretty sure this is do to the compression. You can see it in the figure (showing portion of the file in Hex file editor) that the number of expected bytes per segment doesn't match up!

3.  regarding the ``readZRDFile()`` function -- 

    * Do you think it will be better to discern the file format (compressed vs uncompressed) from the version of the file instead of the caller having to explicitly provide this information? I tend to think that this should be done within the read/write function itself.

    * I have added an optional parameter called ``max_segs_per_ray`` in the ``readZRDFile()`` function, with a default value of ``1000``. One of the main reason for putting this is to prevent the function from crashing if the value of ``n_segment`` (to follow) is read to be a very large number because of unpacking error. I had faced this situation few days back during my test. 

Please have a look at the changes at the following links and let me know what you think.

Branch: 
https://github.com/indranilsinharoy/PyZDDE/tree/zrdFuncFromOlf

test_zrd.py
https://github.com/indranilsinharoy/PyZDDE/blob/zrdFuncFromOlf/Test/zfileutils/test_zrd.py

zfileutils.py
https://github.com/indranilsinharoy/PyZDDE/blob/zrdFuncFromOlf/pyzdde/zfileutils.py


Regards,
Indranil.

**Comment by indranilsinharoy** [comment]
... and I also forgot to add to the above note that I have also changed the type of the ``status`` field in the ``ZemaxRay`` class from ``ctypes.c_int`` to  ``ctypes.c_uint``

**Comment by olfduh** [comment]
Hi Indrail,

I agree about the distinction between the file, actually I already implemented it, just haven't pushed it to github yet... I will try to merge the changes with the new tree in your repository.

About the compressed files, it would be a nice to have feature as the uncompressed ray files are very large. However it is not that critical I think. Also I don't have the time to really spend a lot of work on this problem. 

Regards,

Olf

**Comment by indranilsinharoy** [comment]
"*I agree about the distinction between the file, actually I already implemented it, just haven't pushed it to github yet... I will try to merge the changes with the new tree in your repository.*"   

Great! Also, please consider placing the ``zrd_test.py`` file directly under the ``PyZDDE/Test`` directory. The ``xxx.ZRD`` files required for the test may be placed in a data directory, for example, at ``PyZDDE/test/data/``. 

"*About the compressed files, it would be a nice to have feature as the uncompressed ray files are very large. However it is not that critical I think. Also I don't have the time to really spend a lot of work on this problem*"

Agree completely. We can keep the compressed read/write option unimplemented for now.
This is a significant contribution to PyZDDE. I am hoping many people will benefit from it. Thanks very much.

**Comment by olfduh** [comment]
I merged my branch with your zrdFuncFromOlf branch and solved the conflicts. I pushed all changes to my github repository. There are still some problems which I couldn't solve: My interpreter just jumps over line 219 which declares the comp_type value. Maybe you can quickly see the problem?

**Comment by indranilsinharoy** [comment]
"*My interpreter just jumps over line 219 which declares the comp_type value. Maybe you can quickly *"

I copied that block of code from your branch to the corresponding function in my working branch. It seems to work just fine. Also, I don't see any reason why it won't. Not sure about that.

Also, I just noticed that I had overlooked another thing regarding the differentiation between version number and format number. As per the Zemax manual, my understanding is that all ZRD files have the version number equal to 2001 (which may change in future). They have different format numbers as follows: 
	• 0 for UFD (uncompressed full data) format , 
	• 10000 for CBD (compressed basic) format , and 
	• 20000 for CFD (compressed full data) format . 
	
The version and format numbers are added together and stored in the first integer record in the file , thus the first integer will be: 
	• 2001 for UFD format , 
	• 12001 for CBD format , and 
	• 22001 for CFD format ZRD files.

So, maybe, it would be better to rename the current "version" variable to something like "firstInt". Then, deduce the format number based on the version number, and make decision about the type of file. But we can totally do this sometime later if you are busy right now, .... we can add the current code, because it works, and then clean up some of the places later when time permits. Let me know.

**Comment by olfduh** [comment]
Indrail,
if you check the zfileutils.py file in the ZRD_Support branch you can see that the differentiation between the file versions happens exactly that way :)

**Comment by indranilsinharoy** [comment]
Hi Olf,

It is true the in the code the file type is being inferred based on whether the value of the first int in the file is less than 10000 or greater than 20000, and the code is working just fine. All that I was trying to point out is that they are not the "version" number (as per my understanding of what the Zemax manual says). Please feel free to correct me if you think otherwise. If they are indeed the format numbers, then, I think we should name them as format numbers or we could just test the value of the first int for inferring the file type. Having said that, I will repeat, that if you are satisfied with the current state of the functions, lets clean up the branch and merge it in. We can make incremental changes later on as time permits.

**Comment by olfduh** [comment]
Hi Indrail,

ok now I understand what you mean. That seems easy enough to change the implementation of the version check. I think the only thing that needs to be changed is the condition <10000 to a integer division and maybe change the varaible name. For the current implementation this would not make any difference, only if Zemax introduces a new zrd format it could come in handy...
I see if I can find the time to change it sometime this week.

**Comment by indranilsinharoy** [comment]
Hi Olf,

You just read my mind :-), and I couldn't have explained better perhaps. Thanks.

**Comment by olfduh** [comment]
Indrail,

I pushed the last changes that we discussed. Test function is successful, so I hope the code is ready for the master branch :)

Regards, Olf

**Comment by indranilsinharoy** [comment]
Thanks, Olf. I will try to merge them in tonight. Shall update you after that. 

Best regards,
Indranil.

**Comment by indranilsinharoy** [comment]
Hi Olf,

I was just looking at your latest changes. I noticed that you have added more fields to ``compressed_zrd`` in the ``ZemaxRay`` class. Is there any specific reason for doing so? If you have strong reason to believe that it is required for some reason then we must document it as it might be confusing later on. Also, <s>now that</s> if the structure of ``compressed_zrd`` and ``uncompressed_zrd`` are exactly the same, why do we need two different elements -- ``compressed_zrd`` and ``uncompressed_zrd``? I think we should have just one common element for that (if they are indeed the same).

**Comment by olfduh** [comment]
Hi Indrail,

sorry, I should have documentad that part a bit better. The compressed full data zrd format is the same as the uncompressed full data, but with floating point precision instead of double precision. I changed it as I thought that the CBD format is nearly impossible to import but the CFD might be possible. I haven't really gooten around to check it though... For both CFD and CBD the function will print a warning and return -1. I'd keep it in the code and add a note that it is currently not used or tested.

Regards,

Olf

**Comment by indranilsinharoy** [comment]
Hi Olf,

I finally got some time and merged the zfile utilities from your branch to PyZDDE (after doing some cleanups). While I was doing the final changes before merging, I realized that function `writeZRDfile()` cannot write compressed files (i.e. to either CFD or CBD file types). So, I have added an extra check a `NotImplementedError` exception. I have also modified the simple print statements to `NotImplementedError` exceptions for the same in `readZRDfile()` function. Furthermore, I believe that creating a large list of `ZemaxRay()` class could be very expensive for memory/performance as it is implemented right now. I think we might be able to optimize by using `__slots__` and moving the `compressed_zrd`, `uncompressed_zrd`, `nsq_source_fields` outside the class as their essential function is to help the read and write functions by providing knowledge about the datatype of the various elements (please do correct me if I have misunderstood). These changes can be made over time (as time permits). 
Thank you very much for the contribution. I hope there will be more in future.

**Comment by olfduh** [comment]
Indrail,
It is true, the implementation as is might not be the most efficient way. Not sure if I can continue working on this stuff in the near future. Currently I am trying to get my head around the new .NET interface of Zemax 15. It looks like this offers much better control than the old DDE interface. Still very buggy but it has potential :)

**Comment by indranilsinharoy** [comment]
Hi Olf,

I have experimented with the new .NET interface little bit, and I agree that it is much better than the old DDE. I am sure the interface will get better with time as it is an important feature of OpticStudio.

Best regards,
Indranil.

**Pull request merged**
